config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :status, inclusion: { in: ['not-started','in-progress','completed']}

  STATUS_OPTIONS =[
    ['Not started','not-started'],
    ['In-progress','in-progress'],
    ['Completed','completed']
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [ :show, :edit, :update, :destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.tasks.clear                   # << add this line
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
  end


  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
      if @task.update(task_params)
      redirect_to(@task.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to project_url(@project)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <a class="navbar-brand" href="/">Project Management System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    

      
 

      <% if user_signed_in? %>
        
        <li><%= button_to "Sign Out", destroy_user_session_path, method:'delete' ,class: "nav-link btn btn-outline my-2 my-sm-3"%></li>
      <% else %>
        <li class="nav-item active">
        <%= link_to "Sign Up", new_user_registration_path , class: "nav-link  my-2 my-sm-3"%>
        <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
      </li>
        <li><%= link_to "Log In", new_user_session_path,class: "nav-link  my-2 my-sm-3"%></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>SimplePm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js">

    <%= stylesheet_pack_tag "application", media: 'all', "data-turbo-track": "reload" %>

    <%= javascript_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
          <%= render "layouts/header"%>

    <div class="container pt-3">
           <p class="alert" style="color: green"><%= notice %></p>
       <p class="alert" style="color: green"><%= alert %></p>

    </div>
    <div class="container pt-5">
     
      <div class="card">
       
        <div class="card-body">
           <%= yield %>   
        </div>
      </div>
    </div>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

 </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

 
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-header">
    <h2 class="card-title d-flex justify-content-between">
      <span>Projects</span>
    <%= link_to "New project", new_project_path ,class:"btn btn-primary" %>
    </h2>
  </div>
  <div class="card-body">
    <% @projects.each do |p|%>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to p.name.capitalize , project_path(p) %></h5>
            <p><%= p.description.capitalize %></p>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path , class: "btn btn-outline-info"%>
</div>

app/views/projects/show.html.erb
<div class="card">
  <div class="card-header">
    <h2 class="card-title d-flex justify-content-between">
      <span>    <%= @project.name.capitalize %>     </span>
      <div>
       <%= link_to "Update", edit_project_path(@project),class:"btn btn-outline-warning " %>
       <%= link_to "Back", projects_path ,class:"btn btn-outline-secondary" %>
      </div>
    </h2>
  </div>
  <div class="card-body"><h4>
    <span><strong>Description:</strong> <%= @project.description.capitalize %></span><br><br>
    <span><strong>User: </strong><%= @project.user_id %></span><br><br></h4>
       <%= button_to "Delete", @project, method: :delete ,class: "btn btn-outline-danger btn-sm" %>
  </div>
  
</div>


<hr>
<div class="card">
  <div class="card-header">
    <h2 class="card-title d-flex justify-content-between">Add Task</h2>
  </div>
  <div class="card-body">
    <%= render 'tasks/form' %>
  </div>
</div>
<hr>

<div class="card">
  <div class="card-header">
    <h2 class="card-title d-flex justify-content-between"><span>Listing Tasks</span>
    <div>
      <%= link_to 'New Task', new_project_task_path(@project.id) , class: "btn btn-outline-primary" %>  
    </div></h2>
  </div>
  <div class="card-body">
    <table class="table table-bordered table-hover">

      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Project</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @project.tasks.each do |task| %>
      <% if task.persisted? %>
        <tr>
          <td><%= task.name %></td>
          <td><%= task.description %></td>
          <td><%= task.status %></td>
          <td><%= task.project.name.inspect %></td>
          <td><%= link_to 'Show', [task.project, task], class: "btn btn-outline-info" %></td>
          <td><%= link_to 'Edit', edit_project_task_path(task.project, task),class: "btn btn-outline-warning" %></td>
          <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-outline-danger"%></td>
        </tr>
      <% end %>
    <% end %>
  </table>

  <br />

    
  </div>
  
</div><br>

<center><%= link_to "Back", projects_path ,class:"btn btn-outline-secondary" %></center>
<br>

app/views/tasks/_form.html.erb
        <%= form_for([@task.project, @task]) do |f| %>
      <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
          <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description %>
      </div>
      <div class="field">
        <%= f.label :status %><br />
        <%= f.select :status, Task::STATUS_OPTIONS %>
      </div>
    <br>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

    

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', [@task.project, @task] %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.project.name.inspect %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= button_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<div class="card">
	<div class="card-header">
		<h2 class="card-title d-flex justify-content-between">
			<span>Add Task</span>
			<div>
				<%= link_to 'Back', project_tasks_path(@task.project), class: "btn btn-outline-info" %>

			</div>
		</h2>
	</div>
	<div class="card-body">
		<%= render 'form' %>

	</div>
</div>

app/views/tasks/show.html.erb
<div class="card">
  <div class="card-header">
    <h2 class="card-title d-flex justify-content-between">
      <span>  <%= @task.name.capitalize %> </span>
      <div>
        <%= link_to 'Edit', edit_project_task_path(@task.project, @task) ,class: "btn btn-outline-warning"%>
        <%= link_to 'Back', project_path(@task.project) ,class: "btn btn-outline-secondary"%>
      </div>
    </h2>
  </div>
  <div class="card-body">
    <p>
      <b>Description:</b>
      <%= @task.description.capitalize %>
    </p>

    <p>
      <b>Status:</b>
      <%= @task.status %>
    </p>

    <p>
      <b>Project:</b>
      <%=link_to @project.name.capitalize ,project_path(@project) %>
    </p>

  <%= button_to 'Destroy', [@task.project, @task], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
  </div>

<br>
</div>